### ISSUE TITLE
check-rbl.rb not working

### ISSUE THREAD

**Issue by maticmeznar** [sensu-plugins/sensu-plugins-network-checks#11]
I've gem installed dnsbl-client and sensu-plugin, yet the check fails with the following error:

$ /etc/sensu/plugins/check-rbl.rb
Sensu::Plugin::CLI: ["Not implemented! You should override Sensu::Plugin::CLI#run."]
/usr/share/rubygems/rubygems/core_ext/kernel_require.rb:126:in `require': cannot load such file -- dnsbl-client (LoadError)
        from /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:126:in `require'
        from /etc/sensu/plugins/check-rbl.rb:32:in `<main>'

I'm using CentOS 7.

**Comment by tas50** [comment]
Are you running the plugin with system ruby or the embedded ruby in Sensu?

**Comment by maticmeznar** [comment]
System ruby. I did gem install dnsbl-client and sensu-plugins-network-checks as root.

`$ check-rbl.rb`
``Sensu::Plugin::CLI: ["Not implemented! You should override Sensu::Plugin::CLI#run."]
/usr/share/rubygems/rubygems/core_ext/kernel_require.rb:126:in `require': cannot load such file -- dnsbl-client (LoadError)``

        from /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:126:in `require'
        from /usr/local/share/gems/gems/sensu-plugins-network-checks-0.0.2/bin/check-rbl.rb:32:in `<top (required)>'
        from /usr/local/bin/check-rbl.rb:23:in `load'
        from /usr/local/bin/check-rbl.rb:23:in `<main>'

**Comment by maticmeznar** [comment]
I just did a fresh Sensu install on Ubuntu Vivid Vagrant box and I get the same error. I installed the plugin with "sudo gem install sensu-plugins-network-checks".

``vagrant@vagrant-ubuntu-vivid-64:~$ check-rbl.rb ``
``Sensu::Plugin::CLI: ["Not implemented! You should override Sensu::Plugin::CLI#run."]
/usr/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require': cannot load such file -- dnsbl-client (LoadError)
	from /usr/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /var/lib/gems/2.1.0/gems/sensu-plugins-network-checks-0.0.2/bin/check-rbl.rb:32:in `<top (required)>'
	from /usr/local/bin/check-rbl.rb:23:in `load'
	from /usr/local/bin/check-rbl.rb:23:in `<main>'``

**Comment by mattyjones** [comment]
@maticmeznar  Thanks for bringing this to our attention.  The issue should be fixed now in the latest version.

`/usr/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require': cannot load such file -- dnsbl-client (LoadError) from /usr/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require' from /var/lib/gems/2.1.0/gems/sensu-plugins-network-checks-0.0.2/bin/check-rbl.rb:32:in `<top (required)>' from /usr/local/bin/check-rbl.rb:23:in `load' from /usr/local/bin/check-rbl.rb:23:in `<main>'`

The real error was the require statement, it was `require dnsbl-client` and it should have been `require dnsbl/client`

<img width="837" alt="screen shot 2015-07-06 at 9 35 00 pm" src="https://cloud.githubusercontent.com/assets/672940/8537024/f3c41326-2426-11e5-80d9-f8f638c9fbd8.png">

Fixed

**Comment by SergiuCip** [comment]
Hi, 

The issue seems not to be fixed as I am still getting the same error but with another plugin, what's more is that I can install the gem for eg sensu-plugins as many times as I want, which suggests that is not installing it.

Please help

**Comment by maticmeznar** [comment]
@SergiuCip I now install plugins on sensu-server and sensu-client with:
`$ sensu-install -p <pluginName>`
e.g., `$ sensu-install -p disk-checks`

**Comment by eheydrick** [comment]
@SergiuCip what is the specific plugin and error you are getting?

**Comment by abhinav-h-saxena** [comment]
Hi,
I am getting below error while using sensu and Uchiwa.

$ /etc/sensu/plugins/check-ram.rb -w 20 -c 10
/usr/share/rubygems/rubygems/core_ext/kernel_require.rb:55:in `require': cannot load such file -- sensu-plugin/check/cli (LoadError)
        from /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:55:in `require'
        from /etc/sensu/plugins/check-ram.rb:26:in `<main>'
Any suggestions?

**Comment by jrstjohn** [comment]
@abhinav-h-saxena Make sure that you are setting the PATH and GEM_PATH to use the embedded ruby environment.

If you're using systemd, change the service file's ExecStart directive to something like the following:
`ExecStart=/bin/bash -c 'PATH=/opt/sensu/embedded/bin:$PATH:/etc/sensu/plugins:/etc/sensu/handlers GEM_PATH=/opt/sensu/embedded/lib/ruby/gems/2.3.0:$GEM_PATH /opt/sensu/bin/sensu-client -b -d /etc/sensu/conf.d -e /etc/sensu/extensions -l /var/log/sensu/sensu-client.log -L info'`
